spring:
  profiles:
    active: local
  security:
      user:
       name: user
       password: 1111
  data:
   rest:
    base-path: /api
logging:
   level:
     com:
     gongsik:
     gsw: DEBUG
jasypt:
 encryptor:
   key: ${jasypt-key}
   password: ${jasypt-password}

