spring:
  profiles:
    active: local
    include: oauth
  security:
   oauth2:
    client:
     registration:
      naver:
       client-id: hEDxqGOiNGVCIczz7PJO
       client-secret: FyVkyE7Dx4
       scope:
       - name
       - eamil
       - password
       client-name : naver
       authorization-grant-type : authorization_code
       redirect-uri: http://localhost/login/oauth2/code/naver
       
      google:
       client-id: 404609510825-rlnj3vvidfgc5iku3ls1rrdl5a5hq16v.apps.googleusercontent.com
       client-secret: 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
       scope: email,profile
       client-name : google
       redirect-uri: http://localhost/login/oauth2/code/google
       
      kakao:
        client-id: 487df06077ec2b2eecb7a10d4e48e6dc
        client-secret: nYskHjoiEByQnjJUEI3NhCzLdkZpVEWT
        client-name: kakao
        client-authentication-method: client_secret_post
        authorization-grant-type: authorization_code
        redirect-uri: http://localhost/login/oauth2/code/kakao
        scope:
          - profile_nickname
          - account_email

     provider:
      naver:
       authorization-uri: https://nid.naver.com/oauth2.0/authorize
       token-uri: https://nid.naver.com/oauth2.0/token
       user-info-uri: https://openapi.naver.com/v1/nid/me
       user-name-attribute: response ##회원 정볼르 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
       
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id
       
#   user:
#    name: user
#    password: 1111
  data:
   rest:
    base-path: /api
       
logging:
   level:
     com:
     gongsik:
     gsw: DEBUG
jasypt:
 encryptor:
   key: ${jasypt-key}
   password: ${jasypt-password}
   
  