version: '2'
services:
## mySql
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=gsw'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
    command: --lower_case_table_names=1
    ports:
      - '3306:3306'
    networks:
      - gongsik
## redis
  redis:
    container_name: gongsik-redis
    image: redis:latest  # 레디스 이미지
    ports:
      - '6379:6379'
    networks: 
     - gongsik
## nginx
  nginx:
    container_name: gongsik-nginx
    image: nginx:latest
    ports:
      - '80:80'
    extra_hosts:
      - host.docker,internal:host-gateway
    networks:
      - gongsik
## application
  application:
    build:              ## 빌드
      context: .        ## 빌드할 경로
    ports:
      - 81:8080
    container_name: gsw-backend  ## 컨테이너 이름
    restart: always               ## 매번 프로젝트를 다시 실행한다. 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gsw?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      spring.profiles.active: local                ## 스프링 active profile 설정
    depends_on:                   ## mysql 컨테이너가 올라온 뒤에 이 컨테이너가 올라올 수 있도록 한다.
      - mysql
      - redis
      - nginx
    networks:
      - gongsik
      
networks:
  gongsik:
  